// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VUTCrewBot.DAL;

#nullable disable

namespace VUTCrewBot.DAL.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20221126013140_Reminders")]
    partial class Reminders
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("VUTCrewBot.DAL.Entities.KeyValueSettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("KeyValueSettings");
                });

            modelBuilder.Entity("VUTCrewBot.DAL.Entities.MeetEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MeetupTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Meets");
                });

            modelBuilder.Entity("VUTCrewBot.DAL.Entities.MeetTemplateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DoGenerate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("MeetupDayTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RepeatDay")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MeetTemplates");
                });

            modelBuilder.Entity("VUTCrewBot.DAL.Entities.MeetTemplateUserEntity", b =>
                {
                    b.Property<int>("MeetTemplateId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.HasKey("MeetTemplateId", "UserId");

                    b.ToTable("MeetTemplateUserEntity");
                });

            modelBuilder.Entity("VUTCrewBot.DAL.Entities.ReminderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemindText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RemindTime")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("VUTCrewBot.DAL.Entities.UserMeetResponse", b =>
                {
                    b.Property<int>("MeetId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<byte>("Response")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0);

                    b.HasKey("MeetId", "UserId");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("VUTCrewBot.DAL.Entities.MeetTemplateUserEntity", b =>
                {
                    b.HasOne("VUTCrewBot.DAL.Entities.MeetTemplateEntity", "MeetTemplate")
                        .WithMany("Users")
                        .HasForeignKey("MeetTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeetTemplate");
                });

            modelBuilder.Entity("VUTCrewBot.DAL.Entities.UserMeetResponse", b =>
                {
                    b.HasOne("VUTCrewBot.DAL.Entities.MeetEntity", "Meet")
                        .WithMany("UserResponses")
                        .HasForeignKey("MeetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meet");
                });

            modelBuilder.Entity("VUTCrewBot.DAL.Entities.MeetEntity", b =>
                {
                    b.Navigation("UserResponses");
                });

            modelBuilder.Entity("VUTCrewBot.DAL.Entities.MeetTemplateEntity", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
